import type { Transaction, Account, Budget, Investment, Goal } from "./schemas";

export const sampleTransactions: Transaction[] = [
  {
    id: "1",
    amount: 2500,
    description: "Salary - January 2024",
    category: "Salary",
    type: "income",
    date: new Date("2024-01-15"),
    accountId: "1",
  },
  {
    id: "2",
    amount: 1200,
    description: "Rent Payment",
    category: "Housing",
    type: "expense",
    date: new Date("2024-01-01"),
    accountId: "1",
  },
  {
    id: "3",
    amount: 85.5,
    description: "Grocery Shopping",
    category: "Food & Dining",
    type: "expense",
    date: new Date("2024-01-20"),
    accountId: "1",
  },
  {
    id: "4",
    amount: 45.0,
    description: "Gas Station",
    category: "Transportation",
    type: "expense",
    date: new Date("2024-01-18"),
    accountId: "1",
  },
  {
    id: "5",
    amount: 120.0,
    description: "Electric Bill",
    category: "Utilities",
    type: "expense",
    date: new Date("2024-01-10"),
    accountId: "1",
  },
  {
    id: "6",
    amount: 65.0,
    description: "Internet Bill",
    category: "Utilities",
    type: "expense",
    date: new Date("2024-01-12"),
    accountId: "1",
  },
  {
    id: "7",
    amount: 200.0,
    description: "Freelance Project",
    category: "Freelance",
    type: "income",
    date: new Date("2024-01-22"),
    accountId: "1",
  },
  {
    id: "8",
    amount: 150.0,
    description: "Restaurant Dinner",
    category: "Food & Dining",
    type: "expense",
    date: new Date("2024-01-19"),
    accountId: "1",
  },
  {
    id: "9",
    amount: 89.99,
    description: "Netflix Subscription",
    category: "Entertainment",
    type: "expense",
    date: new Date("2024-01-05"),
    accountId: "1",
  },
  {
    id: "10",
    amount: 300.0,
    description: "Car Insurance",
    category: "Insurance",
    type: "expense",
    date: new Date("2024-01-08"),
    accountId: "1",
  },
];

export const sampleAccounts: Account[] = [
  {
    id: "1",
    name: "Main Checking",
    type: "checking",
    balance: 5240.5,
    currency: "USD",
    color: "#3b82f6",
  },
  {
    id: "2",
    name: "Savings Account",
    type: "savings",
    balance: 15000.0,
    currency: "USD",
    color: "#10b981",
  },
  {
    id: "3",
    name: "Credit Card",
    type: "credit",
    balance: -1250.75,
    currency: "USD",
    color: "#ef4444",
  },
  {
    id: "4",
    name: "Investment Portfolio",
    type: "investment",
    balance: 25000.0,
    currency: "USD",
    color: "#8b5cf6",
  },
];

export const sampleBudgets: Budget[] = [
  {
    id: "1",
    name: "Monthly Groceries",
    amount: 400,
    category: "Food & Dining",
    period: "monthly",
    startDate: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Entertainment Budget",
    amount: 200,
    category: "Entertainment",
    period: "monthly",
    startDate: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Transportation",
    amount: 300,
    category: "Transportation",
    period: "monthly",
    startDate: new Date("2024-01-01"),
  },
];

export const sampleInvestments: Investment[] = [
  {
    id: "1",
    symbol: "AAPL",
    name: "Apple Inc.",
    shares: 10,
    purchasePrice: 150.0,
    purchaseDate: new Date("2023-06-15"),
    accountId: "4",
  },
  {
    id: "2",
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    shares: 5,
    purchasePrice: 2800.0,
    purchaseDate: new Date("2023-08-20"),
    accountId: "4",
  },
  {
    id: "3",
    symbol: "TSLA",
    name: "Tesla Inc.",
    shares: 8,
    purchasePrice: 200.0,
    purchaseDate: new Date("2023-10-10"),
    accountId: "4",
  },
];

export const sampleGoals: Goal[] = [
  {
    id: "1",
    name: "Emergency Fund",
    targetAmount: 10000,
    currentAmount: 8000,
    targetDate: new Date("2024-06-01"),
    category: "Savings",
    priority: "high",
  },
  {
    id: "2",
    name: "Vacation Fund",
    targetAmount: 5000,
    currentAmount: 2500,
    targetDate: new Date("2024-12-01"),
    category: "Travel",
    priority: "medium",
  },
  {
    id: "3",
    name: "New Car",
    targetAmount: 25000,
    currentAmount: 5000,
    targetDate: new Date("2025-06-01"),
    category: "Transportation",
    priority: "low",
  },
];
