export enum CATEGORIES_ENUM {
  FOOD = "FOOD",
  TRANSPORT = "TRANSPORT",
  UTILITIES = "UTILITIES",
  HEALTH = "HEALTH",
  EDUCATION = "EDUCATION",
  DEBTS = "DEBTS",
  SALARY = "SALARY",
  FREELANCE = "FREELANCE",
  INVESTMENTS = "INVESTMENTS",
  OTHER = "OTHER",
}
